theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
cursorline = true
cursorcolumn = true
true-color = true
color-modes = true
rulers = [80, 89]
completion-timeout = 15
auto-format = true

[editor.auto-save]
focus-lost = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
#center = ["file-name"]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "version-control",
  "selections",
  "position",
  "file-encoding",
  "file-type",
]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["diagnostics", "diff", "spacer", "line-numbers"]

[editor.gutters.line-numbers]
min-width = 3

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = true
# Show LSP messages in the status line
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[keys.normal]
"=" = "format_selections"
"space" = { "=" = ":format" }
C-k = "copy_selection_on_prev_line"
C-j = "copy_selection_on_next_line"

[keys.normal.S-d.p]
r = ":run-shell-command uv run %{buffer_name}"
s = ":run-shell-command debugpy --listen 127.0.0.1:5678 --wait-for-client --log-to logs %{buffer_name}"
d = ":debug-remote 127.0.0.1:5678"
